# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-04-13 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beat',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
