# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-01 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats', '0005_beat_beat_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beat',
            options={'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='beat',
            unique_together=set([('title', 'beat_list')]),
        ),
    ]
