# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-05-16 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats', '0006_title_beat_list_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beat_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
